### ISSUE TITLE
No Such Container: mvpn

### ISSUE THREAD

**Issue by KeiranChristie** [bernardko/mullvad-proxy#1]
Hi as the subject headline says, git cloned the repo and input my mullvad account number into .env.example and saved it as .env

I Ran setup.sh as sudo and it ends with "Error: no such container: mvpn"

The whole output is here: https://pastebin.com/DpEFyKEM

**Comment by ronny332** [comment]
I bet you are missing `docker-compose` like me. As the error output is suppressed by the setup script, I had to track it down by hand.

**Comment by Pannekoekjes** [comment]
I have the same issue. Found out that this is the error:

`/var/lib/dpkg/info/mullvad-vpn.postinst: line 6: systemctl: command not found`

Both ubuntu and debian (in docker) seem not to use systemctl. Now trying to make it work.

**Comment by ronny332** [comment]
I got it working, but moved to GlueTun, works perfect, for a huge amount of services.

**Comment by Pannekoekjes** [comment]
Found some post on forums about systemctl. Seems it needs dbus in a container

dbus is in the current Dockerfile, i will search further :) 

`Normally when you run a container you aren’t running an init system. systemctl is a process that communicates with systemd over dbus. If you aren’t running dbus or systemd, I would expect systemctl to fail.`

https://forums.docker.com/t/systemctl-status-is-not-working-in-my-docker-container/9075


@ronny332 Thanks, will look into that. Looks great at first start.

Edit: Thanks, got GlueTun working !

**Comment by CrazyVaclav** [comment]
I get this error:

`67.79 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: process "/bin/sh -c apt-get --yes update &&     apt-get --yes install dbus curl &&     curl -L -o mullvadvpn.deb https://mullvad.net/download/app/deb/latest &&     apt-get --yes install ./mullvadvpn.deb &&     rm -f mullvadvpn.deb &&     apt-get --yes clean &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100`

I tried to build it with Docker version 24.0.7, build afdd53b in debian12 and I use the build in `docker compose` command instead of the python script docker-compose

**Comment by caewok** [comment]
@Pannekoekjes How did you get it to work? Do you have a Dockerfile you can share?

**Comment by Pannekoekjes** [comment]
@caewok I meant that i got GlueTun working. I could not get this proxy to work at the moment. Currently still using GlueTun and it's great.

**Comment by au-ganymede** [comment]
@Pannekoekjes Is GlueTun able to connect to Mullvad and then tunnel traffic through the SOCKS5 proxy so I can connect via Firefox (the aim is to browse the web in Firefox through Mullvad)? My main goal is to separate VPNs to specific browsers on the system. Unfortunately, I don't know much about Docker or networking at all (I'm a designer), so the GlueTun wiki isn't entirely clear to me.

**Comment by Pannekoekjes** [comment]
Yes thats possible but not out of the box. You should add this to a docker compose file together with the gluetun example of course. Add the port 1080 to the gluetun service to allow access to socks5

```
  socks5:
    image: serjs/go-socks5-proxy
    network_mode: "service:gluetun"
    restart: unless-stopped
```

Example compose:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.38.0
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 1080:1080     # Socks5 proxy
    volumes:
      - gluetun-data:/gluetun
    environment:
		xxx
      
  socks5:
    image: serjs/go-socks5-proxy
    network_mode: "service:gluetun"
    restart: unless-stopped
  
volumes:
  gluetun-data:
    name: gluetun-data
```
